filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://host.docker.internal:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "http://host.docker.internal:5601"
