filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "huxpbX_Qe5UfeCZh0F9g"
  ssl.verification_mode: none

setup.kibana:
  host: "http://localhost:5601"

